package com.example.finalyear.model

import com.example.finalyear.math.Const
import com.example.finalyear.core.NavData
import com.example.finalyear.core.ObsDataWithRange
import com.example.finalyear.coord.Xyz
import org.ejml.simple.SimpleMatrix
import kotlin.math.*

data class Ionospheric (
    var alpha: DoubleArray = doubleArrayOf(0.0, 0.0, 0.0, 0.0),
    var beta: DoubleArray = doubleArrayOf(0.0, 0.0, 0.0, 0.0),
) {
    companion object {
        // Applies each pseudorange with klobuchar ionospheric delay
        fun delays(navDataList: List<NavData>,
                   obsDataList: List<ObsDataWithRange>,
                   userPos: Xyz,
                   satPosList: SimpleMatrix,
                   frequencyHz: Double): SimpleMatrix {
            val numOfObs = obsDataList.size
            val ionoDelayList = SimpleMatrix(numOfObs, 1)
            for (i in 0 until numOfObs) {
                ionoDelayList[i] = navDataList[i].iono.klobucharDelayMeters(
                    userPosEcef = userPos,
                    satPosEcef = Xyz.fromMatrixRow(satPosList, row = i),
                    rxTowSec = obsDataList[i].inner.rxTimeNs * 1e-9,
                )
            }
            return ionoDelayList
        }
    }

    // Klobuchar, J.A. (1987) ‘Ionospheric time-delay algorithm for single-frequency GPS users’, IEEE Transactions on Aerospace and Electronic Systems, AES-23(3), pp. 325–331. doi: 10.1109/TAES.1987.310829.
    fun klobucharDelayMeters(
        userPosEcef: Xyz,
        satPosEcef: Xyz,
        rxTowSec: Double,
    ): Double {
        val topocentricAED = userPosEcef.toTopocentricAED(satPosEcef)
        val azimuth = topocentricAED.azimuth
        val elevationRadians = topocentricAED.elevation
        val originWgs = userPosEcef.toPhiLamH()

        val elevationSemiCircle = elevationRadians / PI
        val azimuthSemiCircle = azimuth / PI
        val phiU = originWgs.phi / PI  // Latitude (Φ_u), semi circles
        val lamU = originWgs.lam / PI  // Longitude (λ_u), semi circles

        // Earth's centered angle (semi-turns) (ψ)
        val earthCenteredAngleSemiCircle = 0.0137 / (elevationSemiCircle + 0.11) - 0.022

        // Subionospheric latitude (semi-turns) (Φ_I)
        var phiI = phiU + earthCenteredAngleSemiCircle * cos(azimuthSemiCircle * PI)
        phiI = phiI.coerceIn(-0.416, 0.416)

        // Subionospheric longitude (semi-circles) (λ_I)
        // λ_I = λ_u + ψ sin(A) / cos(Φ_I)
        val lamI = (lamU
            + earthCenteredAngleSemiCircle
                * sin(azimuthSemiCircle * PI)
                / cos(phiI * PI))

        // geomagnetic latitude (semi circles) (Φ_M)
        val phiM = phiI + 0.064 * cos(lamI * PI - 5.08)

        // local time (t)
        var localTimeSec = 86400.0 / 2.0 * lamI + rxTowSec
        localTimeSec = localTimeSec.mod(86400.0)

        // amplitude of the ionospheric delay (seconds)
        val amplitudeOfDelaySeconds = max((
                alpha[0]
                + alpha[1] * phiM
                + alpha[2] * phiM * phiM
                + alpha[3] * phiM * phiM * phiM
        ), 0.0)

        // period of ionospheric delay
        val periodOfDelaySec = max((
                beta[0]
                + beta[1] * phiM
                + beta[2] * phiM * phiM
                + beta[3] * phiM * phiM * phiM
        ), 72000.0)

        // phase of ionospheric delay (x)
        val phaseOfDelay = 2 * PI * (localTimeSec - 50400) / periodOfDelaySec

        // slant factor
        val slantFactor = 1.0 + 16.0 * (0.53 - elevationSemiCircle).pow(3)

        // ionospheric time delay (seconds)
        val ionoDelaySec = if (abs(phaseOfDelay) >= PI / 2.0) {
            5.0e-9 * slantFactor
        } else {
            (5.0e-9
                    + (1
                    - phaseOfDelay.pow(2) / 2.0
                    + phaseOfDelay.pow(4) / 24.0)
                    * amplitudeOfDelaySeconds) * slantFactor
        }

        return ionoDelaySec * Const.c
    }

    // auto generated by Android Studio
    override fun equals(other: Any?): Boolean {
        if (other !is Ionospheric) return false
        return alpha.contentEquals(other.alpha)
                && beta.contentEquals(other.beta)
    }

    // auto generated by Android Studio
    override fun hashCode(): Int {
        var result = alpha.contentHashCode()
        result = 31 * result + beta.contentHashCode()
        return result
    }

    fun clone(): Ionospheric {
        return Ionospheric(
            alpha = alpha.clone(),
            beta = beta.clone(),
        )
    }

    fun clear() {
        alpha = doubleArrayOf(0.0, 0.0, 0.0, 0.0)
        beta = doubleArrayOf(0.0, 0.0, 0.0, 0.0)
    }
}