package com.example.finalyear.dgps

import com.example.finalyear.io.JsonParser.ByteArrayBase64Serializer
import com.example.finalyear.math.GpsTime
import kotlinx.serialization.Serializable
import kotlin.math.floor

const val SYS_GPS = 0x01
const val NUM_SATS = 32

@Serializable
data class Rtcm (
    var t0: GpsTime = GpsTime(0),
    var recvTime: GpsTime = GpsTime(0),
    @Serializable(with = ByteArrayBase64Serializer::class)
    var buff: ByteArray = byteArrayOf(),
    var len: Int = 0,
    var msgType: Int = 0,
    var dgps: MutableList<DgpsCorrection?> = MutableList(NUM_SATS) { null },  // A bucket for all GPS satellites
    var stationId: Int = 0,
    var seqNo: Int = 0,
    var stationHealth: Int = 0,
) {
    companion object {
        // Verifies the satellite comes from GPS and in valid range
        fun satNo(sys: Int, prn: Int): Int? {
            if (sys != SYS_GPS) {
                return null
            }
            if (prn < 1 || prn > 32) {
                return null
            }
            return prn
        }
    }

    fun resizeBuffers() {
        buff = ByteArray(1200)
        dgps = MutableList(NUM_SATS) { null }
    }

    /**
     * Function adapted from:
     * Federal Agency for Cartography and Geodesy (BKG) (2008) RTCM2.cpp.
     * Available at: <https://software.rtcm-ntrip.org/browser/ntrip/trunk/BNC/RTCM/RTCM2.cpp?rev=1044> [Accessed: 25 January 2026].
     */
    fun adjHour(zCount: Double) {
        if (t0.nanos == 0L) {
            t0 = GpsTime.fromUnixNow()
        }
        val (week, tow) = t0.asWeekAndTowSec()
        val hour = floor(tow / 3600).toInt()
        val sec = tow - hour * 3600
        var adjustedZCount = zCount
        if (adjustedZCount < sec - 1800) {
            adjustedZCount += 3600
        } else if (adjustedZCount > sec + 1800) {
            adjustedZCount -= 3600
        }
        t0 = GpsTime.fromWeekAndTowSec(week, (hour * 3600 + adjustedZCount))
    }

    // Returns null if message is not DGPS (Type 1) or no record found for PRN
    fun weightOfSat(prn: Int, gpsTimeSecs: Double): Double? {
        if (msgType != 1) {
            return null
        }
        val dgpsCorrection = dgps[prn - 1] ?: return null
        // Using a heuristic value: sigma = 2^udre
        val sigmaUdre = 2u shl dgpsCorrection.udre
        val varianceUdre = (sigmaUdre * sigmaUdre).toDouble()

        val deltaT = gpsTimeSecs - t0.secs

        // Variance = σ_udre ^ 2 + health * (Δt) ^ 2
        // station health the lower the better
        val variance = varianceUdre + deltaT * deltaT * stationHealth

        // Weight = 1 / σ^2
        return 1 / variance
    }

    fun numDgnss(): Int {
        return dgps.count { it != null }
    }

    // auto generated by Android studio
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as Rtcm

        if (t0 != other.t0) return false
        if (!buff.contentEquals(other.buff)) return false
        if (len != other.len) return false
        if (msgType != other.msgType) return false
        if (dgps != other.dgps) return false
        if (stationId != other.stationId) return false
        if (seqNo != other.seqNo) return false
        if (stationHealth != other.stationHealth) return false

        return true
    }

    // auto generated by Android Studio
    override fun hashCode(): Int {
        var result = t0.hashCode()
        result = 31 * result + buff.contentHashCode()
        result = 31 * result + len
        result = 31 * result + msgType
        result = 31 * result + dgps.hashCode()
        result = 31 * result + stationId
        result = 31 * result + seqNo
        result = 31 * result + stationHealth
        return result
    }
}